### ISSUE TITLE
Error in register_toolchains: register_toolchains() got unexpected keyword argument 'dev_dependency'

### ISSUE THREAD

**Issue by vorburger** [sgammon/rules_graalvm#215]
Running the following on https://github.com/enola-dev/enola/pull/385/commits/28642e5927227a0863486551cb0f2802ba3e24a7 of https://github.com/enola-dev/enola/pull/385 for https://github.com/enola-dev/enola/issues/337 causes the following error (on that initial commit; I'll continue playing with it on that PR, which may evolve):

```bash
$ bazelisk build //...
ERROR: Traceback (most recent call last):
        File "rules_graalvm@0.10.3/MODULE.bazel", line 193, column 20, in <toplevel>
Error in register_toolchains: register_toolchains() got unexpected keyword argument 'dev_dependency'
ERROR: Error computing the main repository mapping: error executing MODULE.bazel file for rules_graalvm@0.10.3
Loading:
```

I suspect this may be because I'm still on Bazel 6.1.2? I'll see if I can easily upgrade.

**Comment by vorburger** [comment]
> I'll see if I can easily upgrade.

Oh, right; I forgot: I cannot (easily), due to https://github.com/bazelbuild/rules_jvm_external/issues/910 ... 😢

**Comment by vorburger** [comment]
> I suspect this may be because I'm still on Bazel 6.1.2? I'll see if I can easily upgrade.

Indeed when using Bazel 6.4.0 instead of 6.1.2 I'm not seeing this problem anymore.

**Comment by sgammon** [comment]
@vorburger Thanks for filing. I'll keep an eye on this and see if it can be worked around in the next release.
