### ISSUE TITLE
Migrate for --incompatible_disallow_ctx_resolve_tools

### ISSUE THREAD

**Issue by meteorcloudy** [sgammon/rules_graalvm#458]
See https://github.com/bazelbuild/bazel/issues/22249

Usage in this repo: 
https://github.com/sgammon/rules_graalvm/blob/986584552f9e08f88e03624a0a29063993447259/internal/native_image/rules.bzl#L61-L63

[rules_graalvm](https://github.com/sgammon/rules_graalvm) is used by Bazel itself, so this is blocking building Bazel with Bazel@HEAD (or upcoming Bazel 8.0).

**Comment by meteorcloudy** [comment]
@sgammon 

FYI @tjgq

**Comment by sgammon** [comment]
Thanks for the tag @meteorcloudy. I'll prioritize a fix for this one.

**Comment by meteorcloudy** [comment]
Downstream failure is now revealed after fixing some other breakages: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4130#0191fe2b-61de-4994-9e6a-d5ee92614f03

**Comment by tjgq** [comment]
https://github.com/sgammon/rules_graalvm/pull/459 fixes this.

**Comment by sgammon** [comment]
@tjgq Thank you kindly

**Comment by meteorcloudy** [comment]
Thanks for the fix! @tjgq 

@sgammon Can you push a new release to the BCR?

**Comment by sgammon** [comment]
@meteorcloudy It's in the works, yeah. Now that #467 is done, I intend to bump to merge #451, perform some cleanup, publish, then add JVM 23, then publish again.

I plan to publish at `0.11.3` and `0.12.0` respectively.

**Comment by meteorcloudy** [comment]
SGTM, thanks!

**Comment by meteorcloudy** [comment]
Gently ping~

**Comment by sgammon** [comment]
@meteorcloudy moving step by step ;) #476
