### ISSUE TITLE
legacy bindist files seems to have a lot of unreachable code

### ISSUE THREAD

**Issue by johnynek** [sgammon/rules_graalvm#57]
e.g. https://github.com/sgammon/rules_graalvm/blob/aedd413d30acaa4d8677c63c1772ff8f26df8c53/internal/graalvm_bindist_legacy.bzl#L85

it seems your code is now looking for things of different shape. If you look in that file and try to figure out how to access those, you can't.

For instance, many have `sha` keys, but your code is looking for `sha256`. Seems like most of that needs to be removed.

I'm can't get it to work yet, so it may still be operator error, but it looks like the legacy stuff doesn't work, so maybe just remove it and have a clear and tested upgrade guide for people who want to create native image binaries.

**Comment by sgammon** [comment]
@johnynek it's supposed to fallback to equivalent code from `rules_graal` when it consults the older bindist map. I'll take a look at this and add an integration test too.
