### ISSUE TITLE
Download GraalVM distributions lazily

### ISSUE THREAD

**Issue by fmeum** [sgammon/rules_graalvm#66]
Bazel only fetches repositories when they are actually needed during the build. By moving the `toolchain` definitions into a separate repo from the actual files comprising the toolchains, this can be used to prevent fetches of large toolchains (such as GraalVM distributions) when not used for a particular build (because the toolchain is never selected).

It would be great if rules_graalvm could support this, potentially by splitting https://github.com/sgammon/rules_graalvm/blob/43adbdccc19821b66f20567ed44fb6bcf10820d1/internal/graalvm_bindist.bzl#L462-L552
into two separate repository rules that are instantiated by a macro.

Context: I am trying to add rules_graalvm to Bazel's remote java tools, but currently this would require anyone who builds Bazel (or really any target in the repo) to also download GraalVM.

**Comment by sgammon** [comment]
@fmeum I believe two repos are already configured -- the [`<name>_toolchain_config_repo` repo](https://github.com/sgammon/rules_graalvm/blob/main/internal/graalvm_bindist.bzl#L649-L686), and the main [`<name>` repo](https://github.com/sgammon/rules_graalvm/blob/aad2b28e9a7c16d4448b3bda0e9871fad7407874/internal/graalvm_bindist.bzl#L529-L556) configured by the user.

repo structure looks like:
```mermaid
flowchart TD
    A(graalvm) -->|Alias| B(graalvm_toolchain_config_repo)
    B-->C[Java toolchain]
    A-->|toolchain target|D[GVM toolchain]

```

`graalvm_toolchain_config_repo` looks like:
```
@graalvm_toolchain_config_repo//:BUILD.bazel (null)
@graalvm_toolchain_config_repo//:bootstrap_runtime_toolchain (9dc7412)
@graalvm_toolchain_config_repo//:gvm (9dc7412)
@graalvm_toolchain_config_repo//:prefix_version_setting (9dc7412)
@graalvm_toolchain_config_repo//:toolchain (9dc7412)
@graalvm_toolchain_config_repo//:version_or_prefix_version_setting (9af774c)
@graalvm_toolchain_config_repo//:version_or_prefix_version_setting (9dc7412)
@graalvm_toolchain_config_repo//:version_setting (9dc7412)
```

`graalvm` looks like:
```
# ...
@graalvm//:sdk (9af774c) → @graalvm//:toolchain_gvm
@graalvm//:toolchain (9af774c) → @graalvm_toolchain_config_repo//:toolchain
@graalvm//:toolchain_gvm (9dc7412) → (see below)
# ...
```
```
toolchain(
  name = "toolchain_gvm",
  toolchain_type = "//graalvm/toolchain:toolchain",
  exec_compatible_with = [],
  target_compatible_with = [],
  toolchain = "@_main~graalvm~graalvm//:gvm",
)
```

So, is the above correct with regard to the Java toolchain, or are you referring to the GVM toolchain used to resolve `native-image`? And if the latter, would moving it to match the Java toolchain structure shown fix the issue? Thanks for your advice here, it is very helpful.

**Comment by fmeum** [comment]
Yes, I was specifically referring to the toolchain for `native_image`, which I believe is in a single repo and would benefit from this optimization.

**Comment by sgammon** [comment]
@fmeum understood, sorry, I was only clarifying because I was wondering if this pattern I saw with Java Toolchains was one and the same with what you're talking about. I should be able to have this change in quickly.
