### ISSUE TITLE
Populate environment for macOS builds

### ISSUE THREAD

**Issue by fmeum** [sgammon/rules_graalvm#67]
While trying to set up rules_graalvm@HEAD within Bazel itself in https://github.com/bazelbuild/bazel/pull/19361, I ran into CI failures on macOS due to the missing environment variable `DEVELOPER_DIR` (see https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/17182#018a41ad-4977-4468-b1ab-523f0710e4ad/513-543).

Could rules_graalvm be missing a call to [`apple_common.target_apple_env`](https://bazel.build/rules/lib/toplevel/apple_common#target_apple_env) or, probably even better, [`apple_support.run`](https://github.com/bazelbuild/apple_support/blob/master/doc/apple_support.md#apple_support.run)?

**Comment by sgammon** [comment]
@fmeum We are definitely missing such calls. So far, the only way I know to initialize the Xcode environment is to [pass those variables through from the `default_shell_env`](https://github.com/sgammon/rules_graalvm/blob/main/internal/native_image/rules.bzl#L188-L197):

https://github.com/sgammon/rules_graalvm/blob/aad2b28e9a7c16d4448b3bda0e9871fad7407874/internal/native_image/rules.bzl#L188-L197

If you know how to prepare the Apple toolchain, I'd love some advice on this topic, or I would be happy to accept a PR. I have a doc with [hermetic compile advice](https://github.com/sgammon/rules_graalvm/blob/main/docs/hermeticity.md#macos) (to the best of my knowledge, of course), and it recommends setting `BAZEL_USE_CPP_ONLY_TOOLCHAIN=1` which isn't ideal. So I can update that too.

I'll take a look these links you've shared to absorb the docs.
